
DROP TABLE IF EXISTS roles CASCADE
DROP TABLE IF EXISTS userinfo CASCADE
DROP TABLE IF EXISTS users

CREATE TABLE users (id SERIAL PRIMARY KEY, email VARCHAR NOT NULL, password VARCHAR NOT NULL, isenabled BOOL DEFAULT TRUE )
CREATE TABLE userinfo (id SERIAL PRIMARY KEY, first_name VARCHAR, last_name VARCHAR, user_id INTEGER, FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE)
CREATE TABLE roles	(id	SERIAL PRIMARY KEY,	name	VARCHAR,	user_id	INTEGER,	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE	)


